artifact_uri: file://Users/rysshe/Documents/CODE/paraphrase/mlflow_tracking/0/585cecec910842c58ed683952ca80496/artifacts
end_time: 1628337955747
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 585cecec910842c58ed683952ca80496
run_uuid: 585cecec910842c58ed683952ca80496
source_name: ''
source_type: 4
source_version: ''
start_time: 1628337955732
status: 3
tags: []
user_id: rysshe
