artifact_uri: file://Users/rysshe/Documents/CODE/paraphrase/mlflow_tracking/0/f21f4e94c6bc44a986d08f2b4ce3b5c1/artifacts
end_time: 1628338255366
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f21f4e94c6bc44a986d08f2b4ce3b5c1
run_uuid: f21f4e94c6bc44a986d08f2b4ce3b5c1
source_name: ''
source_type: 4
source_version: ''
start_time: 1628338255353
status: 3
tags: []
user_id: rysshe
